<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * duJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class duJourRepository extends EntityRepository
{
}
