<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserPersonalInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPersonalInformationRepository extends EntityRepository
{
}
