<?php

namespace AdminBundle\Entity;

namespace AdminBundle\Controller;
use Doctrine\ORM\EntityRepository as EntityRepositorytory;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepositorytory
{
}
